//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Attachment
    {
        public int AuditID { get; set; }
        public string AuditBy { get; set; }
        public string AuditAction { get; set; }
        public Nullable<System.DateTime> AuditTimeStamp { get; set; }
        public Nullable<int> AttachmentID { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public string OwnerTable { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string FileName { get; set; }
        public string FileSize { get; set; }
        public string FileExtension { get; set; }
        public string FileURL { get; set; }
        public string Status { get; set; }
    }
}
