//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_CONTRACT
    {
        public int AUDITID { get; set; }
        public string AUDITACTION { get; set; }
        public string AUDITBY { get; set; }
        public Nullable<System.DateTime> AUDITTIMESTAMP { get; set; }
        public Nullable<int> CONTRACTNUM { get; set; }
        public string ORIGINALCONTRACTNUM { get; set; }
        public string CONTRACTTYPE { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public string SUBJECT { get; set; }
        public Nullable<short> ORGCODE { get; set; }
        public string ORGNAME { get; set; }
        public string PROJECTCODE { get; set; }
        public string PROJECTNAME { get; set; }
        public Nullable<decimal> TOTALAMOUNT { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> STATUSDATE { get; set; }
        public string BUYERCODE { get; set; }
        public string BUYERNAME { get; set; }
        public string CURRENCYCODE { get; set; }
        public Nullable<int> VENDORID { get; set; }
        public string VENDORNAME { get; set; }
        public string VENDORADDR { get; set; }
        public string VENDORATTNNAME { get; set; }
        public string VENDORATTNPOS { get; set; }
        public string VENDORATTNMOB { get; set; }
        public string VENDORATTTEL { get; set; }
        public string VENDOREMAIL { get; set; }
        public string MASTERCONTRACT { get; set; }
    }
}
