//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_POLINE
    {
        public int AUDITID { get; set; }
        public string AUDITACTION { get; set; }
        public string AUDITBY { get; set; }
        public Nullable<System.DateTime> AUDITTIMESTAMP { get; set; }
        public Nullable<long> POLINEID { get; set; }
        public Nullable<decimal> PONUM { get; set; }
        public Nullable<short> POREVISION { get; set; }
        public Nullable<short> POLINENUM { get; set; }
        public string LINETYPE { get; set; }
        public string COSTCODE { get; set; }
        public string CATALOGCODE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> ORDERQTY { get; set; }
        public string ORDERUNIT { get; set; }
        public Nullable<decimal> UNITCOST { get; set; }
        public Nullable<decimal> LINECOST { get; set; }
        public string ITEMNUM { get; set; }
        public string MODELNUM { get; set; }
        public string REQUESTEDBYCODE { get; set; }
        public string REQUESTEDBYNAME { get; set; }
        public Nullable<System.DateTime> REQDELIVERYDATE { get; set; }
        public string MANUFACUTRER { get; set; }
        public string REMARK { get; set; }
        public string TAXCODE { get; set; }
        public Nullable<decimal> TAXTOTAL { get; set; }
        public Nullable<bool> TAXED { get; set; }
        public string ROWSTAMP { get; set; }
        public Nullable<decimal> TAXRATE { get; set; }
        public Nullable<decimal> RECEIPTTOLERANCE { get; set; }
        public string SPECIFICATION { get; set; }
    }
}
