//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_POPERMISSION
    {
        public int AUDITID { get; set; }
        public string AUDITACTION { get; set; }
        public string AUDITBY { get; set; }
        public Nullable<System.DateTime> AUDITTIMESTAMP { get; set; }
        public Nullable<decimal> PONUM { get; set; }
        public string PERMCODE { get; set; }
        public string AUTHBY { get; set; }
        public string JUSTIFICATION { get; set; }
    }
}
