//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_POSignature
    {
        public int AuditPOSignID { get; set; }
        public string AuditBy { get; set; }
        public string AuditAction { get; set; }
        public Nullable<System.DateTime> AuditTimeStamp { get; set; }
        public int POSignID { get; set; }
        public int OrderNo { get; set; }
        public decimal PONum { get; set; }
        public short POREVISION { get; set; }
        public string Authority { get; set; }
        public Nullable<int> Designation { get; set; }
        public string TeamMemberCode { get; set; }
        public string TeamMemberName { get; set; }
    }
}
