//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_PO
    {
        public int AUDITID { get; set; }
        public string AUDITACTION { get; set; }
        public string AUDITBY { get; set; }
        public Nullable<System.DateTime> AUDITTIMESTAMP { get; set; }
        public Nullable<decimal> PONUM { get; set; }
        public string POREF { get; set; }
        public Nullable<long> POSID { get; set; }
        public Nullable<short> POREVISION { get; set; }
        public string DESCRIPTION { get; set; }
        public string ORGCODE { get; set; }
        public string ORGNAME { get; set; }
        public string PROJECTCODE { get; set; }
        public string PROJECTNAME { get; set; }
        public string MRNUM { get; set; }
        public string QNUM { get; set; }
        public Nullable<System.DateTime> QDATE { get; set; }
        public string PAYMENTTERMS { get; set; }
        public Nullable<System.DateTime> ORDERDATE { get; set; }
        public Nullable<System.DateTime> REQUIREDATE { get; set; }
        public Nullable<System.DateTime> VENDORDATE { get; set; }
        public string POTYPE { get; set; }
        public string ORIGINALPONUM { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> STATUSDATE { get; set; }
        public string BUYERCODE { get; set; }
        public string BUYERNAME { get; set; }
        public Nullable<int> VENDORID { get; set; }
        public string VENDORNAME { get; set; }
        public string VENDORADDR { get; set; }
        public string VENDORATTN1NAME { get; set; }
        public string VENDORATTN1POS { get; set; }
        public string VENDORATTN1MOB { get; set; }
        public string VENDORATTN1TEL { get; set; }
        public string VENDORATTN1FAX { get; set; }
        public string VENDORATTN1EMAIL { get; set; }
        public string VENDORATTN2NAME { get; set; }
        public string VENDORATTN2POS { get; set; }
        public string VENDORATTN2MOB { get; set; }
        public string VENDORATTN2TEL { get; set; }
        public string VENDORATTN2FAX { get; set; }
        public string VENDORATTN2EMAIL { get; set; }
        public string SHIPTOADDR { get; set; }
        public string SHIPTOATTN1NAME { get; set; }
        public string SHIPTOATTN1MOB { get; set; }
        public string SHIPTOATTN1POS { get; set; }
        public string SHIPTOATTN2NAME { get; set; }
        public string SHIPTOATTN2MOB { get; set; }
        public string SHIPTOATTN2POS { get; set; }
        public Nullable<int> CONTRACTREFNUM { get; set; }
        public string REVCOMMENTS { get; set; }
        public Nullable<bool> HISTORYFLAG { get; set; }
        public string CURRENCYCODE { get; set; }
        public Nullable<decimal> TOTALTAX { get; set; }
        public Nullable<decimal> PRETAXTOTAL { get; set; }
        public string INTNOTE { get; set; }
        public string EXTNOTE { get; set; }
        public Nullable<bool> SENDNOTETOACCTS { get; set; }
    
        public virtual PO PO { get; set; }
    }
}
