//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Registration
    {
        public int AuditRegistrationID { get; set; }
        public string AuditAction { get; set; }
        public string AuditBy { get; set; }
        public Nullable<System.DateTime> AuditTimeStamp { get; set; }
        public Nullable<int> RegistrationID { get; set; }
        public string RegistrationType { get; set; }
        public string SupplierName { get; set; }
        public string SupplierShortName { get; set; }
        public string Country { get; set; }
        public string SupplierType { get; set; }
        public string BusinessClass { get; set; }
        public string OwnerName { get; set; }
        public string Status { get; set; }
        public string OfficialEmail { get; set; }
        public string ContactFirstName { get; set; }
        public string ContactLastName { get; set; }
        public string ContactPosition { get; set; }
        public string ContactPhone { get; set; }
        public string ContactExtension { get; set; }
        public string ContactMobile { get; set; }
        public string RegDocType { get; set; }
        public string RegDocID { get; set; }
        public string RegDocIssAuth { get; set; }
        public Nullable<System.DateTime> RegDocExpiryDate { get; set; }
        public string VATRegistrationNo { get; set; }
        public Nullable<bool> IsVATRegistered { get; set; }
        public string VATRegistrationType { get; set; }
        public string VATGrpRepName { get; set; }
    
        public virtual Registration Registration { get; set; }
    }
}
