//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_SupplierBankingDetails
    {
        public int AuditBankDetail { get; set; }
        public string AuditAction { get; set; }
        public string AuditBy { get; set; }
        public Nullable<System.DateTime> AuditTimeStamp { get; set; }
        public int SupplierBankDetailID { get; set; }
        public int SupplierID { get; set; }
        public string Country { get; set; }
        public string BankName { get; set; }
        public string BranchAddress { get; set; }
        public string AccountNum { get; set; }
        public string AccountName { get; set; }
        public string IBAN { get; set; }
    
        public virtual SupplierBankingDetail SupplierBankingDetail { get; set; }
    }
}
