//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_UserSecurityGroup
    {
        public int AuditID { get; set; }
        public string AuditBy { get; set; }
        public string AuditAction { get; set; }
        public Nullable<System.DateTime> AuditTimeStamp { get; set; }
        public Nullable<int> SecurityGroupMemberID { get; set; }
        public string UserID { get; set; }
        public Nullable<int> SecurityGroupID { get; set; }
    }
}
