//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_UserProjects
    {
        public int AuditUserProjectID { get; set; }
        public string AuditAction { get; set; }
        public string AuditBy { get; set; }
        public Nullable<System.DateTime> AuditTimeStamp { get; set; }
        public Nullable<int> UserProjID { get; set; }
        public string UserID { get; set; }
        public string OrgCode { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
