//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Users
    {
        public int AuditID { get; set; }
        public string AuditBy { get; set; }
        public string AuditAction { get; set; }
        public Nullable<System.DateTime> AuditTimeStamp { get; set; }
        public string UserID { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Password { get; set; }
        public string Status { get; set; }
        public string Email { get; set; }
        public string PhoneNum { get; set; }
        public string AuthSystem { get; set; }
        public string OrgCode { get; set; }
        public Nullable<int> emp_code { get; set; }
    }
}
