//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class acct_sgrp
    {
        public short acct_sgrp_type { get; set; }
        public short acct_sgrp_mgrp { get; set; }
        public short acct_sgrp_code { get; set; }
        public string acct_sgrp_desc { get; set; }
        public string acct_sgrp_desc_ar { get; set; }
        public bool acct_exclude_os_inv { get; set; }
    
        public virtual acct_mgrp acct_mgrp { get; set; }
    }
}
