//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class acct_mgrp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public acct_mgrp()
        {
            this.acct_sgrp = new HashSet<acct_sgrp>();
        }
    
        public short acct_mgrp_type { get; set; }
        public short acct_mgrp_code { get; set; }
        public string acct_mgrp_desc { get; set; }
        public string acct_mgrp_desc_ar { get; set; }
        public Nullable<byte> acct_mgrp_mode { get; set; }
        public Nullable<short> acct_bspl_mgrp { get; set; }
        public Nullable<short> acct_bspl_sgrp { get; set; }
        public Nullable<short> acct_bspl_det { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acct_sgrp> acct_sgrp { get; set; }
        public virtual acct_type acct_type { get; set; }
    }
}
