//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class branch_master
    {
        public short bm_code { get; set; }
        public string bm_desc { get; set; }
        public Nullable<short> bm_reg_code { get; set; }
        public string bm_desc_arabic { get; set; }
    }
}
