//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class bspl_mgrp_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bspl_mgrp_master()
        {
            this.bspl_sgrp_master = new HashSet<bspl_sgrp_master>();
        }
    
        public short bsplmg_mgrp_code { get; set; }
        public string bsplmg_mgrp_desc { get; set; }
        public string bsplmg_mgrp_desc_ar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bspl_sgrp_master> bspl_sgrp_master { get; set; }
    }
}
