//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class bspl_det_master
    {
        public short bspldt_mgrp_code { get; set; }
        public short bspldt_sgrp_code { get; set; }
        public short bspldt_det_code { get; set; }
        public string bspldt_desc { get; set; }
        public string bspldt_desc_ar { get; set; }
        public Nullable<bool> bspldr_status { get; set; }
    
        public virtual bspl_sgrp_master bspl_sgrp_master { get; set; }
    }
}
