//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class bspl_sgrp_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bspl_sgrp_master()
        {
            this.bspl_det_master = new HashSet<bspl_det_master>();
        }
    
        public short bsplsg_mgrp_code { get; set; }
        public short bsplsg_sgrp_code { get; set; }
        public string bsplsg_sgrp_desc { get; set; }
        public string bsplsg_sgrp_desc_ar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bspl_det_master> bspl_det_master { get; set; }
        public virtual bspl_mgrp_master bspl_mgrp_master { get; set; }
    }
}
