//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class cm_unified_mapping
    {
        public int cm_unified_acct_code { get; set; }
        public short cm_org_code { get; set; }
        public string cm_unified_acct_name { get; set; }
        public Nullable<int> cm_div_acct_code { get; set; }
    }
}
