//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class conso_sup_map_tbl
    {
        public int csm_acct_code { get; set; }
        public short csm_org_code { get; set; }
        public int csm_org_acct_code { get; set; }
        public Nullable<byte> csm_status { get; set; }
        public string csm_created_by { get; set; }
        public Nullable<System.DateTime> csm_created_date { get; set; }
    }
}
