//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class conso_sup_list_tmp
    {
        public short org_code { get; set; }
        public string org_name { get; set; }
        public Nullable<int> sup_acct_code { get; set; }
        public string sup_acct_name { get; set; }
    }
}
