//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class conso_sup_list_dm_final_2
    {
        public Nullable<short> supplier_type_code { get; set; }
        public string supplier_type_name { get; set; }
        public Nullable<short> org_code { get; set; }
        public string org_name { get; set; }
        public Nullable<int> org_acct_code { get; set; }
        public Nullable<int> cm_acct_code { get; set; }
        public int SupID { get; set; }
        public string cm_comp_name { get; set; }
        public string CompContactNameFull { get; set; }
        public string CompContactTitle { get; set; }
        public string CompContactFirst { get; set; }
        public string CompContactLast { get; set; }
        public string CompContactPos { get; set; }
        public string CompMobile { get; set; }
        public string CompPhoneNo { get; set; }
        public string CompExt { get; set; }
        public string CompContactEmail { get; set; }
        public string CompType { get; set; }
        public string CompBC { get; set; }
        public string CompSupType { get; set; }
        public string RegDocType { get; set; }
        public string RegDocID { get; set; }
        public string CompOfficialName { get; set; }
        public string RegDocIssAuth { get; set; }
        public Nullable<System.DateTime> RegDocExpDate { get; set; }
        public string REMARKS { get; set; }
        public string record_proc_status { get; set; }
    }
}
