//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRACTREF
    {
        public System.Guid CONTRACTREFID { get; set; }
        public Nullable<int> CONTRACTNUM { get; set; }
        public string RELATEDCONTRACTTYPE { get; set; }
        public Nullable<int> RELATEDCONTRACTNUM { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATIONDATE { get; set; }
    }
}
