//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractStatusHistory
    {
        public int ContractStatusHistoryID { get; set; }
        public int CONTRACTNUM { get; set; }
        public string OLDSTATUS { get; set; }
        public string NEWSTATUS { get; set; }
        public string MEMO { get; set; }
        public string MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> MODIFICATIONDATE { get; set; }
    
        public virtual CONTRACT CONTRACT { get; set; }
    }
}
