//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_LMS
    {
        public short cm_acct_type { get; set; }
        public short cm_mgrp_code { get; set; }
        public short cm_sgrp_code { get; set; }
        public short cm_acct_serial { get; set; }
        public int cm_acct_code { get; set; }
        public string cm_comp_name { get; set; }
        public string cm_comp_name_ar { get; set; }
        public string cm_comp_name_short { get; set; }
        public string cm_comp_offic_name { get; set; }
        public Nullable<int> cm_sup_id { get; set; }
        public string cm_sup_status { get; set; }
        public Nullable<System.DateTime> cm_sup_status_date { get; set; }
        public string cm_sup_country { get; set; }
        public string cm_sup_bc { get; set; }
        public string cm_comp_type { get; set; }
        public string cm_email { get; set; }
        public string cm_contact_per { get; set; }
        public string cm_contact_pos { get; set; }
        public string cm_mobil { get; set; }
        public string cm_contact_tel { get; set; }
        public string cm_contact_ext { get; set; }
        public string cm_reg_doc_type { get; set; }
        public string cm_license_num { get; set; }
        public string cm_issu_auth { get; set; }
        public Nullable<System.DateTime> cm_license_exp_date { get; set; }
        public Nullable<short> cm_country_code { get; set; }
        public string cm_address1 { get; set; }
        public string cm_address2 { get; set; }
        public string cm_city { get; set; }
        public Nullable<short> cm_city_code { get; set; }
        public Nullable<int> cm_pobox { get; set; }
        public string cm_worktel1 { get; set; }
        public string cm_worktel2 { get; set; }
        public string cm_fax { get; set; }
        public string cm_restel { get; set; }
        public string cm_mcoc_num { get; set; }
        public string cm_url { get; set; }
        public Nullable<short> cm_cuscat_code { get; set; }
        public Nullable<int> cm_retention_acno { get; set; }
        public Nullable<int> cm_advance_acno { get; set; }
        public Nullable<bool> cm_is_subcontr { get; set; }
        public Nullable<short> cm_pay_term { get; set; }
        public Nullable<decimal> cm_cr_limit { get; set; }
        public Nullable<decimal> cm_amt_bal { get; set; }
        public Nullable<decimal> cm_pdc_amount { get; set; }
        public Nullable<System.DateTime> cm_last_inv_date { get; set; }
        public Nullable<System.DateTime> cm_last_rec_date { get; set; }
        public string cm_age_type { get; set; }
        public Nullable<decimal> cm_age_01 { get; set; }
        public Nullable<decimal> cm_age_02 { get; set; }
        public Nullable<decimal> cm_age_03 { get; set; }
        public Nullable<decimal> cm_age_04 { get; set; }
        public Nullable<decimal> cm_age_05 { get; set; }
        public Nullable<decimal> cm_age_06 { get; set; }
        public Nullable<decimal> cm_age_07 { get; set; }
        public Nullable<decimal> cm_age_08 { get; set; }
        public Nullable<decimal> cm_age_09 { get; set; }
        public Nullable<decimal> cm_age_10 { get; set; }
        public Nullable<decimal> cm_age_11 { get; set; }
        public Nullable<decimal> cm_age_12 { get; set; }
        public Nullable<bool> cm_group_company { get; set; }
        public Nullable<bool> cm_assoc_company { get; set; }
        public Nullable<int> cm_salesman_code { get; set; }
        public string cm_vat_reg_no { get; set; }
        public Nullable<byte> cm_acct_status { get; set; }
        public string cm_registered_by { get; set; }
        public string cm_created_by { get; set; }
        public string cm_last_mod_by { get; set; }
        public Nullable<System.DateTime> cm_creation_date { get; set; }
        public Nullable<System.DateTime> cm_last_mod_date { get; set; }
    }
}
