//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldLabel
    {
        public int LabelID { get; set; }
        public string TableName { get; set; }
        public string FieldName { get; set; }
        public string Title { get; set; }
        public string Remarks { get; set; }
    }
}
