//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldHelp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FieldHelp()
        {
            this.ControlFieldRELs = new HashSet<ControlFieldREL>();
        }
    
        public int COLUMNID { get; set; }
        public string DATABASENAME { get; set; }
        public string TABLENAME { get; set; }
        public string COLUMNNAME { get; set; }
        public string COLUMNDESC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlFieldREL> ControlFieldRELs { get; set; }
    }
}
