#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FSPPO")]
	public partial class FXSupplierPortalDataAccessDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public FXSupplierPortalDataAccessDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["FSPPOConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}

       

        public FXSupplierPortalDataAccessDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FXSupplierPortalDataAccessDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FXSupplierPortalDataAccessDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FXSupplierPortalDataAccessDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}

        
            //[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.FIRMS_GetAllProjects")]
            //public int FIRMS_GetAllProjects([global::System.Data.Linq.Mapping.ParameterAttribute(Name="INPUTORGCODE", DbType="Int")] System.Nullable<int> iNPUTORGCODE)
            //{
            //	IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iNPUTORGCODE);
            //	return ((int)(result.ReturnValue));
            //}

            [global::System.Data.Linq.Mapping.FunctionAttribute(Name = "dbo.FIRMS_GetAllProjects")]
        public ISingleResult<FIRMS_GetAllProjects_Result> FIRMS_GetAllProjects([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "INPUTORGCODE", DbType = "Int")] System.Nullable<int> iNPUTORGCODE)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iNPUTORGCODE);
            return ((ISingleResult<FIRMS_GetAllProjects_Result>)(result.ReturnValue));
        }

        [global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PO_ResolvePONUM")]
		public int PO_ResolvePONUM([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OUTPUTPONUM", DbType="Decimal(8,0)")] ref System.Nullable<decimal> oUTPUTPONUM)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), oUTPUTPONUM);
			oUTPUTPONUM = ((System.Nullable<decimal>)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
	}
}
#pragma warning restore 1591
