//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class labour_supply_master
    {
        public int lsm_supp_id { get; set; }
        public string lsm_supp_name { get; set; }
        public string lsm_supp_type { get; set; }
    }
}
