//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationTemplate
    {
        public int NotificationTemplatesID { get; set; }
        public string NotificationTempName { get; set; }
        public string NotificationTemplateDesc { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public Nullable<bool> IsNotificationSend { get; set; }
    }
}
