//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrgRole
    {
        public int ORGROLEID { get; set; }
        public string ORGROLENAME { get; set; }
        public string STATUS { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATIONDATETIME { get; set; }
        public string LASTMODIFIEDBY { get; set; }
        public Nullable<System.DateTime> LASTMODIFIEDDATE { get; set; }
    }
}
