//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    using System.Web.Mvc.Html;
    using System.Web.Mvc.Ajax;
    using FXSupplierPortal.Models;

    public partial class PO
    {
        const string errorMsgsuffix = " field is required.";

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PO()
        {
            this.A_PO = new HashSet<A_PO>();
            //this.errorMsgsuffix = errorMsgsuffix;
        }
        
        public System.Guid POID { get; set; }
        
        public decimal? PONUM { get; set; }
        public string POREF { get; set; }
        public long? POSID { get; set; }
        public short POREVISION { get; set; }
        public string DESCRIPTION { get; set; }
        
        public string ORGCODE { get; set; }
        [Required(ErrorMessage ="Division" + errorMsgsuffix)]
        public string ORGNAME { get; set; }
        [Required]
        public string PROJECTCODE { get; set; }
        [Required(ErrorMessage = "Project" + errorMsgsuffix)]
        public string PROJECTNAME { get; set; }
        public string MRNUM { get; set; }
        public string QNUM { get; set; }
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
        [RegularExpression(@"(^$)|(^\d{2}/\d{2}/\d{4})|(^((\d{1})|(\d{2}))/((\d{1})|(\d{2}))/(\d{4})\s((\d{1})|(\d{2}))[:]{1}((\d{1})|(\d{2}))[:]{1}((\d{1})|(\d{2}))\s((AM)|(PM)))", ErrorMessage = "Quotation Date must be in format mm/dd/yyyy")]
        public Nullable<System.DateTime> QDATE { get; set; }
        public string PAYMENTTERMS { get; set; }

        [Required(ErrorMessage = "OrderDate" + errorMsgsuffix)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
        [RegularExpression(@"(^$)|(^\d{2}/\d{2}/\d{4})|(^((\d{1})|(\d{2}))/((\d{1})|(\d{2}))/(\d{4})\s((\d{1})|(\d{2}))[:]{1}((\d{1})|(\d{2}))[:]{1}((\d{1})|(\d{2}))\s((AM)|(PM)))", ErrorMessage = "Order Date must be in format mm/dd/yyyy")]
        public Nullable<System.DateTime> ORDERDATE { get; set; }

        //[DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
        [RegularExpression(@"(^$)|(^\d{2}/\d{2}/\d{4})|(^((\d{1})|(\d{2}))/((\d{1})|(\d{2}))/(\d{4})\s((\d{1})|(\d{2}))[:]{1}((\d{1})|(\d{2}))[:]{1}((\d{1})|(\d{2}))\s((AM)|(PM)))", ErrorMessage = "Required Date must be in format mm/dd/yyyy")]
        public Nullable<System.DateTime> REQUIREDATE { get; set; }
        
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
        [RegularExpression(@"(^$)|(^\d{2}/\d{2}/\d{4})|(^((\d{1})|(\d{2}))/((\d{1})|(\d{2}))/(\d{4})\s((\d{1})|(\d{2}))[:]{1}((\d{1})|(\d{2}))[:]{1}((\d{1})|(\d{2}))\s((AM)|(PM)))", ErrorMessage = "Vendor Date must be in format mm/dd/yyyy")]
        public Nullable<System.DateTime> VENDORDATE { get; set; }
        [Required]
        public string POTYPE { get; set; }
        public string ORIGINALPONUM { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> STATUSDATE { get; set; }
        
        public string BUYERCODE { get; set; }
        [Required(ErrorMessage = "Buyer" + errorMsgsuffix)]
        public string BUYERNAME { get; set; }
        public Nullable<int> VENDORID { get; set; }
        public string VENDORNAME { get; set; }
        public string VENDORADDR { get; set; }
        public string VENDORATTN1NAME { get; set; }
        public string VENDORATTN1POS { get; set; }
        public string VENDORATTN1MOB { get; set; }
        public string VENDORATTN1TEL { get; set; }
        public string VENDORATTN1FAX { get; set; }
        public string VENDORATTN1EMAIL { get; set; }
        public string VENDORATTN2NAME { get; set; }
        public string VENDORATTN2POS { get; set; }
        public string VENDORATTN2MOB { get; set; }
        public string VENDORATTN2TEL { get; set; }
        public string VENDORATTN2FAX { get; set; }
        public string VENDORATTN2EMAIL { get; set; }
        public string SHIPTOADDR { get; set; }
        public string SHIPTOATTN1NAME { get; set; }
        public string SHIPTOATTN1MOB { get; set; }
        public string SHIPTOATTN1POS { get; set; }
        public string SHIPTOATTN2NAME { get; set; }
        public string SHIPTOATTN2MOB { get; set; }
        public string SHIPTOATTN2POS { get; set; }
        public Nullable<decimal> TOTALCOST { get; set; }
        [Required(ErrorMessage = "Currency" + errorMsgsuffix)]
        public string CURRENCYCODE { get; set; }
        public Nullable<decimal> TOTALTAX { get; set; }
        public Nullable<decimal> PRETAXTOTAL { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATIONDATETIME { get; set; }
        public string LASTMODIFIEDBY { get; set; }
        public Nullable<System.DateTime> LASTMODIFIEDDATE { get; set; }
        public Nullable<int> CONTRACTREFNUM { get; set; }
        public string REVCOMMENTS { get; set; }
        public Nullable<bool> HISTORYFLAG { get; set; }
        public string INTNOTE { get; set; }
        public string EXTNOTE { get; set; }
        public bool SENDNOTETOACCTS { get; set; }

        [Required(ErrorMessage = "PoType" + errorMsgsuffix)]
        public string POTYPETEXT { get; set; }

        public string ORIGINALCONTRACTNUM { get; set; }

        public string CURRENCYNAME { get; set; }

        public string POMODE { get; set; }

        [Required(ErrorMessage ="New Status" + errorMsgsuffix)]
        public POStatusTypes poStatusTypes { get; set; }

        public  string prevPOStatus { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<A_PO> A_PO { get; set; }
    }
}
