//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using FXSupplierPortal.Validators;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class POLINE
    {
        const string errorMsgsuffix = " field is required.";
        public long POLINEID { get; set; }
        public decimal PONUM { get; set; }
        public short POREVISION { get; set; }
        [Required(ErrorMessage = "Line Number" + errorMsgsuffix)]
        public short POLINENUM { get; set; }
        
        public string LINETYPE { get; set; }
        public string COSTCODE { get; set; }
        public string CATALOGCODE { get; set; }
        public string DESCRIPTION { get; set; }

        [Required(ErrorMessage = "Quantity" + errorMsgsuffix)]
        public Nullable<decimal> ORDERQTY { get; set; }
        [Required(ErrorMessage = "Order Unit" + errorMsgsuffix)]
        public string ORDERUNIT { get; set; }

        //[RegularExpression(@"^\d+\.\d{0,2}$")]
        [Required(ErrorMessage = "Unit Price" + errorMsgsuffix)]
        public Nullable<decimal> UNITCOST { get; set; }
        //[RegularExpression(@"^\d+\.\d{0,2}$")]
        [Required(ErrorMessage = "Line Cost" + errorMsgsuffix)]
        public Nullable<decimal> LINECOST { get; set; }

        //[Required(ErrorMessage = "Item" + errorMsgsuffix)]
        
        [LineTypeValidator(ErrorMessage ="Item field is required")]
        public string ITEMNUM { get; set; }
        public string MODELNUM { get; set; }
        public string REQUESTEDBYCODE { get; set; }
        public string REQUESTEDBYNAME { get; set; }
        public Nullable<System.DateTime> REQDELIVERYDATE { get; set; }
        public string MANUFACUTRER { get; set; }
        public string REMARK { get; set; }
        public string TAXCODE { get; set; }
        public Nullable<decimal> TAXTOTAL { get; set; }
        public bool TAXED { get; set; }
        public string ROWSTAMP { get; set; }
        public Nullable<decimal> TAXRATE { get; set; }
        public Nullable<System.DateTime> CREATIONDATE { get; set; }
        public string CREATEDBY { get; set; }
        public string LASTMODIFIEDBY { get; set; }
        public Nullable<System.DateTime> LASTMODIFIEDDATE { get; set; }
        public Nullable<decimal> RECEIPTTOLERANCE { get; set; }
        public string SPECIFICATION { get; set; }

        public bool RECEIPTCOMPLETED { get; set; }
        public decimal? RECEIVEDQTY { get; set; }

        public decimal? RECEIVEDCOST { get; set; }

        public string STATUS { get; set; }

        public string POLINEMODE { get; set; }
    }
}
