//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class POPERMISSION
    {
        public int POPERMISSIONID { get; set; }
        public Nullable<decimal> PONUM { get; set; }
        public string PERMCODE { get; set; }
        public Nullable<int> AUTHBYCODE { get; set; }
        public string AUTHBYNAME { get; set; }
        public string AUTHBYPOS { get; set; }
        public string JUSTIFICATION { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATIONDATE { get; set; }
        public string LASTMODIFIEDBY { get; set; }
        public Nullable<System.DateTime> LASTMODIFIEDDATE { get; set; }
    }
}
