//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class POREVISIONHISTORY
    {
        public int POREVISIONHISTORYID { get; set; }
        public Nullable<decimal> PONUM { get; set; }
        public Nullable<short> POREVISION { get; set; }
        public string REVSTATUS { get; set; }
        public string REVCOMMENTS { get; set; }
        public string MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> LASTMODIFIEDDATE { get; set; }
    }
}
