//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class POSignature
    {
        public int POSignID { get; set; }
        public string OrgCode { get; set; }
        public int OrderNo { get; set; }
        public decimal PONum { get; set; }
        public short PoRevision { get; set; }
        public string Authority { get; set; }
        [Required(ErrorMessage = "Designation field is required")]
        public Nullable<int> Designation { get; set; }
        [Required(ErrorMessage = "User field is required")]
        public string TeamMemberCode { get; set; }
        public string TeamMemberName { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationDateTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }

        public string pOSignatureMode { get; set; }
    }
}
