//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_master
    {
        public string project_code { get; set; }
        public string project_desc { get; set; }
        public string project_client { get; set; }
        public string projet_consultant { get; set; }
    }
}
