//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Registration()
        {
            this.A_Registration = new HashSet<A_Registration>();
            this.RegistrationStatusHistories = new HashSet<RegistrationStatusHistory>();
            this.RegSupplierAddresses = new HashSet<RegSupplierAddress>();
        }
    
        public int RegistrationID { get; set; }
        public string RegistrationType { get; set; }
        public string SupplierName { get; set; }
        public string SupplierShortName { get; set; }
        public string Country { get; set; }
        public string SupplierType { get; set; }
        public string BusinessClass { get; set; }
        public string OwnerName { get; set; }
        public string Status { get; set; }
        public string OfficialEmail { get; set; }
        public string ContactFirstName { get; set; }
        public string ContactLastName { get; set; }
        public string ContactPosition { get; set; }
        public string ContactPhone { get; set; }
        public string ContactExtension { get; set; }
        public string ContactMobile { get; set; }
        public string RegDocType { get; set; }
        public string RegDocID { get; set; }
        public string VATRegistrationNo { get; set; }
        public Nullable<bool> IsVATRegistered { get; set; }
        public string VATRegistrationType { get; set; }
        public string VATGrpRepName { get; set; }
        public string RegDocIssAuth { get; set; }
        public Nullable<System.DateTime> RegDocExpiryDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationDateTime { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<A_Registration> A_Registration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistrationStatusHistory> RegistrationStatusHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegSupplierAddress> RegSupplierAddresses { get; set; }
    }
}
