//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_LookUpMap
    {
        public int LookupMapID { get; set; }
        public string SourceTable { get; set; }
        public string SourceColumn { get; set; }
        public string SourceValue { get; set; }
        public string DesTable { get; set; }
        public string DesColumn { get; set; }
        public string DesValue { get; set; }
    }
}
