//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_Messages
    {
        public int MessageID { get; set; }
        public string MessageGroup { get; set; }
        public string Value { get; set; }
        public string Description { get; set; }
        public string MessageType { get; set; }
    }
}
