//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_Permission
    {
        public int PermissionID { get; set; }
        public Nullable<int> PageID { get; set; }
        public string PermissionName { get; set; }
        public string PermissionDesc { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
