//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_SecurityGroupPermission
    {
        public int SecurityGroupPermissionID { get; set; }
        public Nullable<int> SecurityGroupID { get; set; }
        public Nullable<int> PageID { get; set; }
        public string Permission { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> PermissionID { get; set; }
    }
}
