//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_UserLoginActivity
    {
        public string UserID { get; set; }
        public Nullable<System.DateTime> LastChangePassword { get; set; }
        public Nullable<bool> ChangePassOnFirstLogin { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public Nullable<System.DateTime> LastLogoutTime { get; set; }
        public string LastLoginMacAddress { get; set; }
        public string LastLoginIPAddress { get; set; }
    
        public virtual User User { get; set; }
    }
}
