//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class STG_FIRMS_SUPPLIER
    {
        public System.Guid STG_FIRMS_SUPPLIER_ID { get; set; }
        public int TransID { get; set; }
        public string TransEvent { get; set; }
        public string TransStatus { get; set; }
        public string TransError { get; set; }
        public Nullable<System.DateTime> TransDateTime { get; set; }
        public Nullable<System.DateTime> TransStatusDateTime { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public string SupplierStatus { get; set; }
        public Nullable<System.DateTime> SupplierStatusDateTime { get; set; }
        public string SupplierName { get; set; }
        public string SupplierType { get; set; }
        public string Country { get; set; }
        public string BusinessClass { get; set; }
        public string OwnerName { get; set; }
        public string OfficialEmail { get; set; }
        public string ContactPerson { get; set; }
        public string ContactPosition { get; set; }
        public string ContactMobile { get; set; }
        public string ContactPhone { get; set; }
        public string ContactExt { get; set; }
        public string RegDocType { get; set; }
        public string RegDocID { get; set; }
        public string VATRegistrationNo { get; set; }
        public Nullable<bool> IsVATRegistered { get; set; }
        public string VATRegistrationType { get; set; }
        public string VATGrpRepName { get; set; }
        public string RegDocIssAuth { get; set; }
        public Nullable<System.DateTime> RegDocExpiryDate { get; set; }
        public string AddressCountry { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressCity { get; set; }
        public string AddressPostalCode { get; set; }
        public string AddressPhoneNum { get; set; }
        public string AddressFaxNum { get; set; }
        public string SupplierShortName { get; set; }
        public string RegisteredBy { get; set; }
    }
}
