//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class supply_labour_employee
    {
        public int sle_supp_id { get; set; }
        public string sle_hemp_code { get; set; }
        public string sle_hemp_name { get; set; }
        public string sle_eid_no { get; set; }
    }
}
