//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierBankingDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SupplierBankingDetail()
        {
            this.A_SupplierBankingDetails = new HashSet<A_SupplierBankingDetails>();
        }
    
        public int SupplierBankDetailID { get; set; }
        public int SupplierID { get; set; }
        public string Country { get; set; }
        public string BankName { get; set; }
        public string BranchAddress { get; set; }
        public string AccountNum { get; set; }
        public string AccountName { get; set; }
        public string IBAN { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationDateTime { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<A_SupplierBankingDetails> A_SupplierBankingDetails { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
