//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Password { get; set; }
        public string Status { get; set; }
        public string Email { get; set; }
        public string PhoneNum { get; set; }
        public string AuthSystem { get; set; }
        public string OrgCode { get; set; }
        public Nullable<int> emp_code { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationDateTime { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDateTime { get; set; }
    
        public virtual SS_UserLoginActivity SS_UserLoginActivity { get; set; }
    }
}
