//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSession
    {
        public int ID { get; set; }
        public string SessionID { get; set; }
        public string UserID { get; set; }
        public string IPAddress { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> LogonTime { get; set; }
        public Nullable<System.DateTime> LogoutTime { get; set; }
        public string MacAddress { get; set; }
    }
}
