//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewAllSupplierAudit
    {
        public string Status { get; set; }
        public string StatusID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public int AuditID { get; set; }
        public string SupplierName { get; set; }
        public string SupplierShortName { get; set; }
        public string Country { get; set; }
        public string SupplierTypeID { get; set; }
        public string BusinessClassification { get; set; }
        public string OfficialEmail { get; set; }
        public string RegDocType { get; set; }
        public string RegDocID { get; set; }
        public string RegDocIssAuth { get; set; }
        public Nullable<System.DateTime> RegDocExpiryDate { get; set; }
        public string PaymentMethod { get; set; }
        public string DomainName { get; set; }
        public string SupplierType { get; set; }
        public string ContactFirstName { get; set; }
        public string ContactLastName { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDateTime { get; set; }
        public string ContactPosition { get; set; }
        public string ContactPhone { get; set; }
        public string ContactExtension { get; set; }
        public string ContactMobile { get; set; }
    }
}
