//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewAllPurchaseOrderTemplate
    {
        public string POTEMPLATENAME { get; set; }
        public string POTEMPLATEDESC { get; set; }
        public string POType { get; set; }
        public Nullable<int> VENDORID { get; set; }
        public string VENDORNAME { get; set; }
        public string POTYpeID { get; set; }
        public int POTEMPLATEID { get; set; }
        public string ORGNAME { get; set; }
        public string PROJECTNAME { get; set; }
        public Nullable<System.DateTime> CREATIONDATETIME { get; set; }
        public string CREATEDBY { get; set; }
        public string CREATEDBYID { get; set; }
    }
}
