//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewLoadAllRole
    {
        public string PageName { get; set; }
        public string Permission { get; set; }
        public int SecurityGroupPermissionID { get; set; }
        public int PageID { get; set; }
        public string PageURL { get; set; }
        public int SecurityGroupID { get; set; }
        public string SecurityGroupName { get; set; }
    }
}
