//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewAllChangeRequest
    {
        public string SupplierName { get; set; }
        public Nullable<System.DateTime> CreationDateTime { get; set; }
        public int ChangeRequestID { get; set; }
        public int SupplierID { get; set; }
        public string Status { get; set; }
        public string Memo { get; set; }
        public string StatusID { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByuserID { get; set; }
        public System.Guid ID { get; set; }
        public string Value { get; set; }
    }
}
