//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_COST_CODE_MASTER
    {
        public string orgCode { get; set; }
        public string orgName { get; set; }
        public string ccm_type { get; set; }
        public string ccm_serial { get; set; }
        public string ccm_cost_code { get; set; }
        public string ccm_desc { get; set; }
        public Nullable<byte> ccm_status { get; set; }
    }
}
