//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_MATRECTRANS
    {
        public Nullable<int> mrvm_org_code { get; set; }
        public short mrvm_vr_loc { get; set; }
        public int mrvm_vr_no { get; set; }
        public Nullable<int> mrvm_po_no { get; set; }
        public Nullable<short> mrvm_po_rev { get; set; }
        public short mrvd_serial_no { get; set; }
        public Nullable<long> mrvd_po_line_id { get; set; }
        public Nullable<short> mrvd_po_line_no { get; set; }
        public string mrvd_item_code { get; set; }
        public Nullable<decimal> mrvd_rcvd_order_unit { get; set; }
        public Nullable<decimal> mrvd_unit_rate_lc { get; set; }
        public Nullable<decimal> mrvd_value_fc { get; set; }
        public Nullable<decimal> mrvd_line_vat { get; set; }
        public string mrvd_createdBy { get; set; }
        public Nullable<System.DateTime> mrvd_creationDate { get; set; }
        public string mrvd_LastModifiedBy { get; set; }
        public Nullable<System.DateTime> mrvd_LastModifiedDate { get; set; }
    }
}
