//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_PRODUCT_MASTER
    {
        public string orgCode { get; set; }
        public string orgName { get; set; }
        public string prm_item_code { get; set; }
        public string prm_item_desc { get; set; }
        public Nullable<short> prm_uom_code { get; set; }
        public string uom_desc { get; set; }
    }
}
