//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ProjectPOSignatures
    {
        public Nullable<bool> dgt_desig_status { get; set; }
        public string dgt_desig_name { get; set; }
        public string OrgCode { get; set; }
        public int OrderNo { get; set; }
        public decimal PONum { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationDateTime { get; set; }
        public short PoRevision { get; set; }
        public Nullable<int> Designation { get; set; }
        public int POSignID { get; set; }
        public string Authority { get; set; }
        public string EmployeeName { get; set; }
    }
}
