//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_POLINERECEIVING
    {
        public decimal PONUM { get; set; }
        public short POREVISION { get; set; }
        public short POLINENUM { get; set; }
        public long POLINEID { get; set; }
        public Nullable<decimal> ORDERQTY { get; set; }
        public Nullable<decimal> UNITCOST { get; set; }
        public Nullable<decimal> LINECOST { get; set; }
        public Nullable<decimal> TAXTOTAL { get; set; }
        public decimal RECEIVEDQTY { get; set; }
        public Nullable<decimal> REMAININGQTY { get; set; }
        public Nullable<decimal> RECEIPTTOLERANCE { get; set; }
        public Nullable<decimal> RECEIPTTOLQTY { get; set; }
        public Nullable<decimal> RECEIPTTOLAMT { get; set; }
        public Nullable<decimal> RECEIVEDTOTALCOST { get; set; }
        public string RECEIPTSTATUS { get; set; }
    }
}
