//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_PORECEIVING
    {
        public string ORGCODE { get; set; }
        public string PROJECTCODE { get; set; }
        public Nullable<int> VENDORCODE { get; set; }
        public decimal PONUM { get; set; }
        public short POREVISION { get; set; }
        public Nullable<decimal> PRETAXRECEIVINGTOTALCOST { get; set; }
        public Nullable<decimal> RECEIVINGTOTALCOST { get; set; }
        public Nullable<decimal> RECEIVEDTOTALCOST { get; set; }
        public string RECEIPTSTATUS { get; set; }
    }
}
