//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXSupplierPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SUPPYMTTRANS
    {
        public Nullable<int> SUPPLIERID { get; set; }
        public Nullable<int> SUPACCTCODE { get; set; }
        public Nullable<short> VORGCODE { get; set; }
        public string PROJECTCODE { get; set; }
        public string PROJECTNAME { get; set; }
        public Nullable<System.DateTime> VDATE { get; set; }
        public byte VTYPE { get; set; }
        public string VTYPEDESC { get; set; }
        public int VMNUM { get; set; }
        public Nullable<short> VDNUM { get; set; }
        public Nullable<int> INVOICENUM { get; set; }
        public string PONUM { get; set; }
        public Nullable<bool> POEXEMPT { get; set; }
        public Nullable<decimal> VAMOUNT { get; set; }
        public Nullable<byte> VSTATUS { get; set; }
        public string VSTATUSDESC { get; set; }
        public Nullable<System.DateTime> INVOICEDATE { get; set; }
        public Nullable<short> INVPAYTERM { get; set; }
        public Nullable<System.DateTime> INVOICEDUEDATE { get; set; }
    }
}
